# Generated by Django 5.0.6 on 2024-05-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username_user_avatar_user_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='телеграмм chat-id'),
        ),
    ]
